version: 2
models:
  - name: int_local_bikes__customers
    description: "Intermediate model that enriches customer data with derived fields"
    columns:
      - name: customer_id
        description: "{{ doc('stg_local_bikes__customers__customer_id') }}"
        tests:
          - unique
          - not_null
      - name: customer_first_name
        description: "{{ doc('stg_local_bikes__customers__customer_first_name') }}"
      - name: customer_last_name
        description: "{{ doc('stg_local_bikes__customers__customer_last_name') }}"
      - name: customer_name
        description: "{{ doc('int_local_bikes__customer_name') }}"
      - name: customer_phone
        description: "{{ doc('stg_local_bikes__customers__customer_phone') }}"
      - name: customer_email
        description: "{{ doc('stg_local_bikes__customers__customer_email') }}"
      - name: customer_street
        description: "{{ doc('stg_local_bikes__customers__customer_street') }}"
      - name: customer_city
        description: "{{ doc('stg_local_bikes__customers__customer_city') }}"
      - name: customer_state
        description: "{{ doc('stg_local_bikes__customers__customer_state') }}"
      - name: customer_zip_code
        description: "{{ doc('stg_local_bikes__customers__customer_zip_code') }}"

  - name: int_local_bikes__order_items
    description: "Intermediate model that enriches order items with calculated pricing fields"
    columns:
      - name: order_item_id
        description: "{{ doc('stg_local_bikes__order_items__order_item_id') }}"
        tests:
          - unique
          - not_null
      - name: order_id
        description: "{{ doc('stg_local_bikes__order_items__order_id') }}"
      - name: item_id
        description: "{{ doc('stg_local_bikes__order_items__item_id') }}"
      - name: product_id
        description: "{{ doc('stg_local_bikes__order_items__product_id') }}"
      - name: quantity
        description: "{{ doc('stg_local_bikes__order_items__quantity') }}"
      - name: list_price
        description: "{{ doc('stg_local_bikes__order_items__list_price') }}"
      - name: discount
        description: "{{ doc('stg_local_bikes__order_items__discount') }}"
      - name: customer_price
        description: "{{ doc('int_local_bikes__customer_price') }}"
      - name: total_price
        description: "{{ doc('int_local_bikes__total_price') }}"
      - name: total_customer_price
        description: "{{ doc('int_local_bikes__total_customer_price') }}"

  - name: int_local_bikes__orders
    description: "Intermediate model for orders"
    columns:
      - name: order_id
        description: "{{ doc('stg_local_bikes__orders__order_id') }}"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "{{ doc('stg_local_bikes__orders__customer_id') }}"
      - name: store_id
        description: "{{ doc('stg_local_bikes__orders__store_id') }}"
      - name: staff_id
        description: "{{ doc('stg_local_bikes__orders__staff_id') }}"
      - name: order_status
        description: "{{ doc('stg_local_bikes__orders__order_status') }}"
      - name: order_date
        description: "{{ doc('stg_local_bikes__orders__order_date') }}"
      - name: order_required_date
        description: "{{ doc('stg_local_bikes__orders__order_required_date') }}"
      - name: order_shipped_date
        description: "{{ doc('stg_local_bikes__orders__order_shipped_date') }}"

  - name: int_local_bikes__products
    description: "Intermediate model for products enriched with brand and category names"
    columns:
      - name: product_id
        description: "{{ doc('stg_local_bikes__products__product_id') }}"
        tests:
          - unique
          - not_null
      - name: brand_id
        description: "{{ doc('stg_local_bikes__products__brand_id') }}"
      - name: category_id
        description: "{{ doc('stg_local_bikes__products__category_id') }}"
      - name: product_name
        description: "{{ doc('stg_local_bikes__products__product_name') }}"
      - name: brand_name
        description: "{{ doc('stg_local_bikes__brands__brand_name') }}"
      - name: category_name
        description: "{{ doc('stg_local_bikes__categories__category_name') }}"
      - name: model_year
        description: "{{ doc('stg_local_bikes__products__model_year') }}"
      - name: list_price
        description: "{{ doc('stg_local_bikes__products__list_price') }}"

  - name: int_local_bikes__staffs
    description: "Intermediate model for staff members"
    columns:
      - name: staff_id
        description: "{{ doc('stg_local_bikes__staffs__staff_id') }}"
        tests:
          - unique
          - not_null
      - name: store_id
        description: "{{ doc('stg_local_bikes__staffs__store_id') }}"
      - name: manager_id
        description: "{{ doc('stg_local_bikes__staffs__manager_id') }}"
      - name: staff_first_name
        description: "{{ doc('stg_local_bikes__staffs__staff_first_name') }}"
      - name: staff_last_name
        description: "{{ doc('stg_local_bikes__staffs__staff_last_name') }}"
      - name: staff_email
        description: "{{ doc('stg_local_bikes__staffs__staff_email') }}"
      - name: staff_phone
        description: "{{ doc('stg_local_bikes__staffs__staff_phone') }}"
      - name: is_active_staff
        description: "{{ doc('stg_local_bikes__staffs__is_active_staff') }}"

  - name: int_local_bikes__stocks
    description: "Intermediate model for stock inventory"
    columns:
      - name: stock_id
        description: "{{ doc('stg_local_bikes__stocks__stock_id') }}"
        tests:
          - unique
          - not_null
      - name: store_id
        description: "{{ doc('stg_local_bikes__stocks__store_id') }}"
      - name: product_id
        description: "{{ doc('stg_local_bikes__stocks__product_id') }}"
      - name: quantity
        description: "{{ doc('stg_local_bikes__stocks__quantity') }}"

  - name: int_local_bikes__stores
    description: "Intermediate model for stores"
    columns:
      - name: store_id
        description: "{{ doc('stg_local_bikes__stores__store_id') }}"
        tests:
          - unique
          - not_null
      - name: store_name
        description: "{{ doc('stg_local_bikes__stores__store_name') }}"
      - name: store_phone
        description: "{{ doc('stg_local_bikes__stores__store_phone') }}"
      - name: store_email
        description: "{{ doc('stg_local_bikes__stores__store_email') }}"
      - name: store_street
        description: "{{ doc('stg_local_bikes__stores__store_street') }}"
      - name: store_city
        description: "{{ doc('stg_local_bikes__stores__store_city') }}"
      - name: store_state
        description: "{{ doc('stg_local_bikes__stores__store_state') }}"
      - name: store_zip_code
        description: "{{ doc('stg_local_bikes__stores__store_zip_code') }}"